### ISSUE TITLE
Guard-minitest does not seem to work with spring in a Rails 4 engine.

### ISSUE THREAD

**Issue by davidmles** [guard/guard-minitest#114] opened 2014-06-01 23:36 UTC
Guard-minitest does not seem to work with spring in a Rails 4 engine.

Steps to reproduce it:
```
rails plugin new example --mountable
cd example/
echo "gem 'guard-minitest', group: :development" >> Gemfile
bundle
bundle exec guard init minitest
bundle exec guard
```

Here it runs the test/example_test.rb sample test successfully:
```
01:27:50 - INFO - Guard is using TerminalTitle to send notifications.
01:27:50 - INFO - Guard::Minitest 2.3.0 is running, with Minitest::Unit 5.3.4!
01:27:50 - INFO - Running: all tests
Run options: --seed 27937

# Running:

.

Finished in 0.004659s, 214.6383 runs/s, 214.6383 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips

01:27:52 - INFO - Guard is now watching at '/Users/david/Sites/example'
```

Now when editing Guardfile and changing ```guard :minitest do``` to ```guard :minitest, spring: true do```, the test is not run anymore:
```
01:28:45 - INFO - Run all
01:28:45 - INFO - Running: all tests
```

Nothing is run.

- Uncommenting the Rails 4 watches gives the same result.
- Adding spring to the Gemfile does not help.
- Stubbing spring into bins after creating this config/spring.rb file:
```
Spring.application_root = './test/dummy'
```
...does not help either.

**Comment by bikramwp** [comment] 2015-01-14 18:59
Just tested this in a Rails engine.
`spring: 'bundle exec spring rake test'` works
but `spring: true` does not work.

I'll make a testrepo

Versions in use:
rails-4.2.0
spring-1.2.0
minitest-5.5.1
guard-2.11.1
guard-minitest-2.3.2

**Comment by e2** [comment] 2015-01-14 22:34
It's because `bin/rake` doesn't exist...

There should be a message in guard-minitest for this. I'll try and cook something up.

**Comment by e2** [comment] 2015-01-15 01:58
I've released guard-minitest 2.4.2, which shows an error in this scenario (instead of a silent failure).

So, I'm closing this.

Let me know if there are any other issues.

**Closed by e2** 2015-01-15 01:58 UTC

**Comment by e2** [comment] 2015-01-15 02:01
@bikramwp - thanks so much for the repo to reproduce this. I wouldn't have worked this out without it.

**Comment by genericsteele** [comment] 2015-01-15 15:26
@e2 Good find and good fix. Thanks for picking this one back up.

**Comment by e2** [comment] 2015-01-15 20:34
@genericsteele - I don't know if Errno::ENOENT is a good choice. But it was the least confusing that I could think of.

**Comment by darmenise** [comment] 2015-07-11 08:53
Uhm, i found out that, for some reason, this issue occurs if there is `spec` folder along with the `test` one. I was migrating from rspec to minitest and I was trying to solve this issue but I gave up. Anyway, as soon as I renamed the `spec` folder the issue was fixed... weird.
